mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=${{ secrets.DB_USER }}
    - MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }}
    - MYSQL_DATABASE=${{ secrets.DB_NAME }}
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
